baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'waris reshi'
theme = 'blank'

[menu]
[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 10
[[menu.main]]
identifier = "notes"
name = "notes"
url = "/notes/"
weight = 20
[[menu.main]]
identifier = "books"
name = "books" 
url = "/books/"
weight = 30
[[menu.main]]
identifier = "stats"
name = "stats"
url = "/stats/"
weight = 40

[taxonomies]
tag = "tags"
category = "categories"
